version: '3'
services:
  planner:
    build:
      context: .
      dockerfile: planner/Dockerfile
    depends_on:
      - gen_worker
      - mult_worker
      - add_worker
    networks:
      - mynetwork
    ports:
      - "3000:3000"

  gen_worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    networks:
      - mynetwork
    deploy:
      replicas: 10
  
  mult_worker:
    image: image/worker
    depends_on:
      - gen_worker
    networks:
      - mynetwork
    environment:
      - ADD=false
    deploy:
      replicas: 10
  
  add_worker:
    image: image/worker
    depends_on:
      - gen_worker
    networks:
      - mynetwork
    environment:
      - MULT=false
    deploy:
      replicas: 10



networks:
  mynetwork:
    driver: bridge